[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
solc-version = "0.8.15"

[profile.v3utilslinker]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
solc-version = "0.8.15"

libraries = [
    'src/Nfpm.sol:Nfpm:0xf2C5C597cfB0bd73F8042F2c3021Dd9FB5297f0E'
]

[profile.linker]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
solc-version = "0.8.15"

libraries = [
    'src/StructHash.sol:StructHash:0x11F5813BC3A0E4d97B24878f6bD2601dF9A682eD',
    'src/Nfpm.sol:Nfpm:0xf2C5C597cfB0bd73F8042F2c3021Dd9FB5297f0E'
]
